categories:
  expressApplePay:
    label: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:category.expressApplePay'
    parent: payment

settings:
  products.express.applepay.merchantIdentifier:
    type: string
    default: ''
    label: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:setting.merchantIdentifier'
    description: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:setting.merchantIdentifier.description'
    category: expressApplePay
  products.express.applepay.displayName:
    type: string
    default: ''
    label: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:setting.displayName'
    description: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:setting.displayName.description'
    category: expressApplePay
  products.express.applepay.countryCode:
    type: string
    default: ''
    label: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:setting.countryCode'
    description: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:setting.countryCode.description'
    category: expressApplePay
  products.express.applepay.apiBaseUrl:
    type: string
    default: ''
    label: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:setting.apiBaseUrl'
    description: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:setting.apiBaseUrl.description'
    category: expressApplePay
  products.express.applepay.apiKey:
    type: string
    default: ''
    label: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:setting.apiKey'
    description: 'LLL:EXT:products_express_apple_pay/Resources/Private/Language/locallang_settings.xlf:setting.apiKey.description'
    category: expressApplePay
