services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GoldeneZeiten\Products\Core\Tests\Functional\Fixtures\TestMailer:
    public: true

  TYPO3\CMS\Core\Mail\MailerInterface:
    alias: GoldeneZeiten\Products\Core\Tests\Functional\Fixtures\TestMailer
    public: true
